CONTACT_FIELDS_DRC = {
    "date_of_birth": "STRING",
    "opt_in_date": "TIMESTAMP",
    "opt_out_date": "TIMESTAMP",
    "optout_reason": "STRING",
    "first_name": "STRING",
    "surname": "STRING",
    "about": "STRING",
    "age_range": "STRING",
    "alerts": "STRING",
    "concern_or_rumour": "STRING",
    "gender": "STRING",
    "healthcare_worker_identification": "STRING",
    "how_did_you_hear_this_rumour": "STRING",
    "job": "STRING",
    "messaging": "STRING",
    "newspapers": "STRING",
    "online": "STRING",
    "wom": "STRING",
    "town_or_city": "STRING",
    "television": "STRING",
    "suburb": "STRING",
    "send_in_a_question": "STRING",
    "report": "STRING",
    "radio": "STRING",
    "other": "STRING",
}
CONTACT_FIELDS_IC = {
    "chills": "STRING",
    "date_of_birth": "TIMESTAMP",
    "district": "STRING",
    "doses": "STRING",
    "emergency_room": "STRING",
    "fatigue_or_tiredness": "STRING",
    "feeling": "STRING",
    "fever_check": "STRING",
    "firstname": "STRING",
    "gender": "STRING",
    "get_care": "STRING",
    "headache": "STRING",
    "health_impact_other": "STRING",
    "hospitalised": "STRING",
    "image_received": "STRING",
    "itching": "STRING",
    "joint_pains": "STRING",
    "manufacturer": "STRING",
    "manufacturer_other": "STRING",
    "meds_for_symptoms": "STRING",
    "miss_work": "STRING",
    "month": "STRING",
    "muscle_or_body_pains": "STRING",
    "normal_daily_activities": "STRING",
    "onset_date": "STRING",
    "opt_in_date": "STRING",
    "opt_out_confirmation": "STRING",
    "opt_out_date": "STRING",
    "other_care": "STRING",
    "outpatient": "STRING",
    "pain": "STRING",
    "reaction_rating": "STRING",
    "redness": "STRING",
    "region": "STRING",
    "reminders": "STRING",
    "result_3": "STRING",
    "results_1": "STRING",
    "results_2": "STRING",
    "signs_presented_disappear": "STRING",
    "site_reaction": "STRING",
    "surname": "STRING",
    "swelling": "STRING",
    "symptoms_medication_name": "STRING",
    "time_of_day": "STRING",
    "vaccination_site": "STRING",
    "year_of_birth": "STRING"
}
GROUP_CONTACT_FIELDS = {"group_uuid": "STRING", "contact_uuid": "STRING"}
GROUP_FIELDS = {"name": "STRING", "uuid": "STRING"}
FLOWS_FIELDS = {"labels": "STRING", "name": "STRING", "uuid": "STRING"}
FLOW_RUNS_FIELDS = {
    "modified_on": "TIMESTAMP",
    "responded": "BOOLEAN",
    "contact_uuid": "STRING",
    "flow_uuid": "STRING",
    "exit_type": "STRING",
    "created_at": "TIMESTAMP",
    "exited_on": "TIMESTAMP",
    "id": "INTEGER",
}
FLOW_RUN_VALUES_FIELDS = {
    "input": "STRING",
    "time": "TIMESTAMP",
    "category": "STRING",
    "name": "STRING",
    "value": "STRING",
    "run_id": "INTEGER",
}
